<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-4-g7f85cfe  Build Version: 1.6.7995.38578
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot name="box_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="box_height" value="0.53"/>
  <xacro:property name="box_width" value="1"/>
  <xacro:property name="box_length" value="0.43"/>
  <xacro:macro name="table_1" params="prefix x y z theta">
    <link name="${prefix}_box_base_link"/>
    <joint name="${prefix}_box_base_joint" type="fixed">
      <origin xyz="${x} ${y} ${z}" rpy="0 0 ${theta}" />
      <parent link="world" />
      <child link="${prefix}_box_base_link" />
      <axis xyz="0 0 0" />
    </joint>

    <link name="${prefix}_box_link">
      <visual>
        <origin xyz="0 0 ${-box_height/2}" rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
        <material name="">
          <color rgba="0.564705882352941 0.564705882352941 0.564705882352941 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 ${-box_height/2}" rpy="0 0 0" />
        <geometry>
          <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_box_joint" type="fixed">
      <origin xyz="0 0 ${box_height}" rpy="0 0 0" />
      <parent link="${prefix}_box_base_link" />
      <child link="${prefix}_box_link" />
      <axis xyz="0 0 0" />
    </joint>

    <!-- <link name="${prefix}_box_link">
      <visual>
        <origin xyz="0 0 ${-box_height/2}" rpy="0 0 0" />
        <geometry>
            <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
        <material name="">
          <color rgba="0.564705882352941 0.564705882352941 0.564705882352941 1" />
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="${box_length} ${box_width} ${box_height}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${prefix}_box_joint" type="fixed">
      <origin xyz="0 0 ${box_height}" rpy="0 0 0" />
      <parent link="${prefix}_box_base_link" />
      <child link="${prefix}_box_link" />
      <axis xyz="0 0 0" />
    </joint> -->
  </xacro:macro>
</robot>